### ISSUE TITLE
RuntimeError: Distributed package doesn't have MPI built in. MPI is only included if you build PyTorch from source on a host that has MPI installed.

### ISSUE THREAD

**Issue by Hangyul-Son** [epfml/federated-learning-public-code#8]
Hello. Happy new year! Thank you for the wonderful code. 

After I built image "user/pytorch-mpi", I ran the image using the command  `"docker run --rm -it -v $PWD:/py -w /py user/pytorch-mpi"` from the root of the repository. Then when I executed the updated version of the command  (pytorch-py3.6 => pytorch-py3.8.12) below,

`$HOME/conda/envs/pytorch-py3.8.12/bin/python3 [run.py](http://run.py/) \
--arch resnet8 --complex_arch master=resnet8,worker=resnet8 --experiment demo \
--data cifar10 --pin_memory True --batch_size 64 --num_workers 2 \
--partition_data non_iid_dirichlet --non_iid_alpha 1 --train_data_ratio 1 --val_data_ratio 0.1 \
--n_clients 20 --participation_ratio 0.1 --n_comm_rounds 100 --local_n_epochs 40 --world_conf 0,0,1,1,100 --on_cuda True \
--fl_aggregate scheme=federated_average \
--optimizer sgd --lr 0.1 --local_prox_term 0 --lr_warmup False --lr_warmup_epochs 5 --lr_warmup_epochs_upper_bound 150 \
--lr_scheduler MultiStepLR --lr_decay 0.1 \
--weight_decay 0 --use_nesterov False --momentum_factor 0 \
--track_time True --display_tracked_time True --python_path $HOME/conda/envs/pytorch-py3.8.12/bin/python3 --hostfile hostfile \
--manual_seed 7 --pn_normalize True --same_seed_process False`

However, even so the code would first throw an runtime error `ModuleNotFoundError: No module named 'torchcontrib'`

Therefore, I installed the module through `pip install torchcontrib`

After that, when I run the same code once again, now it throws an error below,

`Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main(conf)
  File "main.py", line 19, in main
    dist.init_process_group("mpi")
  File "/home/user/conda/envs/pytorch-py3.8.12/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 744, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/user/conda/envs/pytorch-py3.8.12/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 837, in _new_process_group_helper
    raise RuntimeError(
RuntimeError: Distributed package doesn't have MPI built in. MPI is only included if you build PyTorch from source on a host that has MPI installed.`

However, things started to get weird because I remember that docker-compose file installed MPI.

May you review "pytorch-mpi/Dockerfile" file once again, please?

Thank you

**Comment by tlin-taolin** [comment]
if you built the image successfully, one potential reason could be that PyTorch is reinstalled by `torchcontrib`. I think you could build `torchcontrib` from the source if necessary, or you can directly remove this package (it is only used in [swa](https://github.com/epfml/federated-learning-public-code/blob/master/codes/FedDF-code/pcode/aggregation/swa_knowledge_transfer.py))

**Comment by Hangyul-Son** [comment]
Thank you for the reply. I fixed the error following your first advice. 

From your first advice, I built torchcontrib from the source https://github.com/pytorch/contrib by modifying the pytorch-mpi/Dockerfile. Now torchcontrib is part of the image. However, now the below error occurs. 

`ModuleNotFoundError: No module named 'gpytorch'`

From what I searched, gpytorch is a library to enable GPU-supported machine learning systems, which is quite important for FL simulations. I don't think it is removable. Therefore I also installed gpytorch from the source by modifying the Dockerfile. 

Would it be okay for me to open a pull request with the following updates on the Dockerfile for people's convenience in the future?

As always, thank you.

**Comment by Marshall0214** [comment]
Hello, I also encountered the same problem, can you provide the modified dockerfile?

**Comment by tlin-taolin** [comment]
maybe you can use this [one](https://github.com/LINs-lab/FedTHE/blob/master/env/Dockerfile)?

**Comment by Marshall0214** [comment]
Thanks, but the `torchcontrib` and `gpytorch` versions are not included. When I pip `torchcontrib==0.0.2` and `gpytorch==1.0.0`, I still encounter
`RuntimeError: Distributed package doesn't have MPI built in. MPI is only included if you build PyTorch from source on a host that has MPI installed.`

**Comment by namelesspoor** [comment]
> 谢谢，但不包括和版本。当我 pip 和 时，我仍然遇到`torchcontrib``gpytorch``torchcontrib==0.0.2``gpytorch==1.0.0` `RuntimeError: Distributed package doesn't have MPI built in. MPI is only included if you build PyTorch from source on a host that has MPI installed.`

I had the same problem. Did you solve it？
